// <auto-generated />
using System;
using ManageStudents.Infrastructure.Contexts.ManageStudents;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageStudents.Infrastructure.Contexts.ManageStudents.Migrations
{
    [DbContext(typeof(ManageStudentsContext))]
    [Migration("20250918070238_CreateTeacher")]
    partial class CreateTeacher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManageStudents.Domain.Entities.TeacherEntity", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(5);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(2);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(9);

                    b.HasKey("TeacherId");

                    b.HasIndex("DocumentNumber", "Mobile", "Email")
                        .IsUnique();

                    b.ToTable("Teacher", "dbo");

                    b.HasData(
                        new
                        {
                            TeacherId = new Guid("8a05ac05-874c-4613-b29e-6fcd8feac250"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "9831047265",
                            Email = "ana.pineda@demo.edu",
                            Firstname = "Ana",
                            Lastname = "Pineda",
                            Mobile = "3007123845",
                            Subject = "Mathematics",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("ec5598c7-d66e-4197-ba2b-ba75d31c7227"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "1203984756",
                            Email = "luis.montoya@demo.edu",
                            Firstname = "Luis",
                            Lastname = "Montoya",
                            Mobile = "3019837264",
                            Subject = "Spanish",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("c9dbbc9c-cff7-45f8-8578-dedd939aa239"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "6572039184",
                            Email = "claudia.herrera@demo.edu",
                            Firstname = "Claudia",
                            Lastname = "Herrera",
                            Mobile = "3021749382",
                            Subject = "Biology",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("44d3a8bf-a043-4587-a642-c4905c775e70"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "3049182736",
                            Email = "jorge.valencia@demo.edu",
                            Firstname = "Jorge",
                            Lastname = "Valencia",
                            Mobile = "3048261937",
                            Subject = "PoliticalScience",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("bc6d7998-128e-4e30-afa9-6aa7a3af9b85"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "8493027165",
                            Email = "marcela.cruz@demo.edu",
                            Firstname = "Marcela",
                            Lastname = "Cruz",
                            Mobile = "3059172836",
                            Subject = "Chemistry",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("4e6b055a-4699-4c61-a476-f2a98f23cc54"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "7102938465",
                            Email = "ricardo.salinas@demo.edu",
                            Firstname = "Ricardo",
                            Lastname = "Salinas",
                            Mobile = "3103847261",
                            Subject = "Physics",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("2356f96f-fa55-4b35-86c9-4dcbc0d04924"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "5928371046",
                            Email = "patricia.mora@demo.edu",
                            Firstname = "Patricia",
                            Lastname = "Mora",
                            Mobile = "3119283746",
                            Subject = "PhysicalEducation",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("e81bfaa9-dc56-4703-b3dd-1564fc21d33a"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "4382910675",
                            Email = "fernando.garcia@demo.edu",
                            Firstname = "Fernando",
                            Lastname = "García",
                            Mobile = "3126471938",
                            Subject = "Mathematics",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("e41385d8-e050-4ac3-a924-c3237731dace"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "6293847102",
                            Email = "sandra.luna@demo.edu",
                            Firstname = "Sandra",
                            Lastname = "Luna",
                            Mobile = "3138294750",
                            Subject = "Chemistry",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TeacherId = new Guid("686692a7-2cbc-42c9-97b1-f99cdc454edb"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DocumentNumber = "3759102846",
                            Email = "hector.ruiz@demo.edu",
                            Firstname = "Héctor",
                            Lastname = "Ruiz",
                            Mobile = "3147382916",
                            Subject = "Physics",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
